#!/bin/bash
# Compiles multiple assembly files and links
# ./build output_file_name asm1.s asm2.s ...
# generates output_file_name.hex


args=("$@")			# Get all arguments passed and save array with name args

for((i=1; i < $# ; i++))
	do
		input=${args[i]}
		input=$(echo $input|cut -d'.' -f 1)
		params=$params$input".o "
		avr-gcc -W -g -c -mmcu=atmega328p -o $input.o ${args[i]}
	done

avr-ld -e init  -o ${args[0]}.elf $params
avr-objcopy -O ihex ${args[0]}.elf ${args[0]}.hex

rm $params
